export type Lang = "de" | "en" | "fr" | "it";
export type Group = "mammal" | "bird" | "reptile" | "amphibian" | "fish" | "insect" | "other";
export type Region = "ch" | "eu" | "world";

export type Species = {
  latin: string;
  wiki: string;
  group: Group;
  region: Region;
  names: Record<Lang, string>;
  clip: string;
};

export const GROUPS: { id: Group; clip: string; names: Record<Lang, string> }[] = [
  { id: "mammal", clip: "a mammal", names: { de: "Säugetier", en: "mammal", fr: "mammifère", it: "mammifero" } },
  { id: "bird", clip: "a bird", names: { de: "Vogel", en: "bird", fr: "oiseau", it: "uccello" } },
  { id: "reptile", clip: "a reptile", names: { de: "Reptil", en: "reptile", fr: "reptile", it: "rettile" } },
  { id: "amphibian", clip: "an amphibian", names: { de: "Amphibie", en: "amphibian", fr: "amphibien", it: "anfibio" } },
  { id: "fish", clip: "a fish", names: { de: "Fisch", en: "fish", fr: "poisson", it: "pesce" } },
  { id: "insect", clip: "an insect", names: { de: "Insekt", en: "insect", fr: "insecte", it: "insetto" } },
  { id: "other", clip: "a spider, snail, worm or other invertebrate", names: { de: "Anderes", en: "other", fr: "autre", it: "altro" } },
];

export const SPECIES: Species[] = [
  { latin: "Vulpes vulpes", wiki: "Red_fox", group: "mammal", region: "ch", clip: "a red fox", names: { de: "Rotfuchs", en: "red fox", fr: "renard roux", it: "volpe rossa" } },
  { latin: "Meles meles", wiki: "European_badger", group: "mammal", region: "ch", clip: "a European badger", names: { de: "Dachs", en: "European badger", fr: "blaireau européen", it: "tasso" } },
  { latin: "Capreolus capreolus", wiki: "Roe_deer", group: "mammal", region: "ch", clip: "a roe deer", names: { de: "Reh", en: "roe deer", fr: "chevreuil", it: "capriolo" } },
  { latin: "Cervus elaphus", wiki: "Red_deer", group: "mammal", region: "ch", clip: "a red deer stag", names: { de: "Rothirsch", en: "red deer", fr: "cerf élaphe", it: "cervo nobile" } },
  { latin: "Rupicapra rupicapra", wiki: "Chamois", group: "mammal", region: "ch", clip: "a chamois", names: { de: "Gämse", en: "chamois", fr: "chamois", it: "camoscio" } },
  { latin: "Capra ibex", wiki: "Alpine_ibex", group: "mammal", region: "ch", clip: "an Alpine ibex", names: { de: "Steinbock", en: "Alpine ibex", fr: "bouquetin", it: "stambecco" } },
  { latin: "Sus scrofa", wiki: "Wild_boar", group: "mammal", region: "ch", clip: "a wild boar", names: { de: "Wildschwein", en: "wild boar", fr: "sanglier", it: "cinghiale" } },
  { latin: "Lepus europaeus", wiki: "European_hare", group: "mammal", region: "ch", clip: "a European hare", names: { de: "Feldhase", en: "European hare", fr: "lièvre d'Europe", it: "lepre europea" } },
  { latin: "Sciurus vulgaris", wiki: "Red_squirrel", group: "mammal", region: "ch", clip: "a Eurasian red squirrel", names: { de: "Eichhörnchen", en: "red squirrel", fr: "écureuil roux", it: "scoiattolo rosso" } },
  { latin: "Marmota marmota", wiki: "Alpine_marmot", group: "mammal", region: "ch", clip: "an Alpine marmot", names: { de: "Alpenmurmeltier", en: "Alpine marmot", fr: "marmotte des Alpes", it: "marmotta alpina" } },
  { latin: "Erinaceus europaeus", wiki: "European_hedgehog", group: "mammal", region: "ch", clip: "a European hedgehog", names: { de: "Igel", en: "hedgehog", fr: "hérisson", it: "riccio" } },
  { latin: "Castor fiber", wiki: "Eurasian_beaver", group: "mammal", region: "ch", clip: "a Eurasian beaver", names: { de: "Biber", en: "Eurasian beaver", fr: "castor d'Eurasie", it: "castoro europeo" } },
  { latin: "Lutra lutra", wiki: "Eurasian_otter", group: "mammal", region: "ch", clip: "a Eurasian otter", names: { de: "Fischotter", en: "otter", fr: "loutre", it: "lontra" } },
  { latin: "Lynx lynx", wiki: "Eurasian_lynx", group: "mammal", region: "ch", clip: "a Eurasian lynx", names: { de: "Luchs", en: "Eurasian lynx", fr: "lynx boréal", it: "lince europea" } },
  { latin: "Canis lupus", wiki: "Wolf", group: "mammal", region: "ch", clip: "a gray wolf", names: { de: "Wolf", en: "wolf", fr: "loup", it: "lupo" } },
  { latin: "Ursus arctos", wiki: "Brown_bear", group: "mammal", region: "eu", clip: "a brown bear", names: { de: "Braunbär", en: "brown bear", fr: "ours brun", it: "orso bruno" } },
  { latin: "Felis catus", wiki: "Cat", group: "mammal", region: "ch", clip: "a domestic cat", names: { de: "Hauskatze", en: "cat", fr: "chat", it: "gatto" } },
  { latin: "Canis familiaris", wiki: "Dog", group: "mammal", region: "ch", clip: "a domestic dog", names: { de: "Hund", en: "dog", fr: "chien", it: "cane" } },
  { latin: "Bos taurus", wiki: "Cattle", group: "mammal", region: "ch", clip: "a cow", names: { de: "Kuh", en: "cow", fr: "vache", it: "mucca" } },
  { latin: "Ovis aries", wiki: "Sheep", group: "mammal", region: "ch", clip: "a sheep", names: { de: "Schaf", en: "sheep", fr: "mouton", it: "pecora" } },
  { latin: "Capra hircus", wiki: "Goat", group: "mammal", region: "ch", clip: "a domestic goat", names: { de: "Ziege", en: "goat", fr: "chèvre", it: "capra" } },
  { latin: "Equus caballus", wiki: "Horse", group: "mammal", region: "ch", clip: "a horse", names: { de: "Pferd", en: "horse", fr: "cheval", it: "cavallo" } },
  { latin: "Sus domesticus", wiki: "Pig", group: "mammal", region: "ch", clip: "a domestic pig", names: { de: "Schwein", en: "pig", fr: "cochon", it: "maiale" } },
  { latin: "Oryctolagus cuniculus", wiki: "European_rabbit", group: "mammal", region: "ch", clip: "a rabbit", names: { de: "Kaninchen", en: "rabbit", fr: "lapin", it: "coniglio" } },
  { latin: "Martes foina", wiki: "Beech_marten", group: "mammal", region: "ch", clip: "a beech marten", names: { de: "Steinmarder", en: "beech marten", fr: "fouine", it: "faina" } },
  { latin: "Sciurus carolinensis", wiki: "Eastern_gray_squirrel", group: "mammal", region: "eu", clip: "a grey squirrel", names: { de: "Grauhörnchen", en: "grey squirrel", fr: "écureuil gris", it: "scoiattolo grigio" } },
  { latin: "Panthera leo", wiki: "Lion", group: "mammal", region: "world", clip: "a lion", names: { de: "Löwe", en: "lion", fr: "lion", it: "leone" } },
  { latin: "Panthera tigris", wiki: "Tiger", group: "mammal", region: "world", clip: "a tiger", names: { de: "Tiger", en: "tiger", fr: "tigre", it: "tigre" } },
  { latin: "Ailuropoda melanoleuca", wiki: "Giant_panda", group: "mammal", region: "world", clip: "a giant panda", names: { de: "Panda", en: "giant panda", fr: "panda géant", it: "panda gigante" } },
  { latin: "Elephas maximus", wiki: "Asian_elephant", group: "mammal", region: "world", clip: "an elephant", names: { de: "Elefant", en: "elephant", fr: "éléphant", it: "elefante" } },
  { latin: "Giraffa camelopardalis", wiki: "Giraffe", group: "mammal", region: "world", clip: "a giraffe", names: { de: "Giraffe", en: "giraffe", fr: "girafe", it: "giraffa" } },
  { latin: "Equus quagga", wiki: "Zebra", group: "mammal", region: "world", clip: "a zebra", names: { de: "Zebra", en: "zebra", fr: "zèbre", it: "zebra" } },
  { latin: "Phascolarctos cinereus", wiki: "Koala", group: "mammal", region: "world", clip: "a koala", names: { de: "Koala", en: "koala", fr: "koala", it: "koala" } },
  { latin: "Macropus rufus", wiki: "Red_kangaroo", group: "mammal", region: "world", clip: "a kangaroo", names: { de: "Känguru", en: "kangaroo", fr: "kangourou", it: "canguro" } },
  { latin: "Delphinus delphis", wiki: "Common_dolphin", group: "mammal", region: "eu", clip: "a dolphin", names: { de: "Delfin", en: "dolphin", fr: "dauphin", it: "delfino" } },
  { latin: "Orcinus orca", wiki: "Orca", group: "mammal", region: "world", clip: "an orca killer whale", names: { de: "Orca", en: "orca", fr: "orque", it: "orca" } },
  { latin: "Ursus maritimus", wiki: "Polar_bear", group: "mammal", region: "world", clip: "a polar bear", names: { de: "Eisbär", en: "polar bear", fr: "ours polaire", it: "orso polare" } },
  { latin: "Alopex lagopus", wiki: "Arctic_fox", group: "mammal", region: "world", clip: "an arctic fox", names: { de: "Polarfuchs", en: "arctic fox", fr: "renard arctique", it: "volpe artica" } },
  { latin: "Procyon lotor", wiki: "Raccoon", group: "mammal", region: "eu", clip: "a raccoon", names: { de: "Waschbär", en: "raccoon", fr: "raton laveur", it: "procione" } },
  { latin: "Nyctereutes procyonoides", wiki: "Common_raccoon_dog", group: "mammal", region: "eu", clip: "a raccoon dog", names: { de: "Marderhund", en: "raccoon dog", fr: "chien viverrin", it: "cane procione" } },
  { latin: "Anas platyrhynchos", wiki: "Mallard", group: "bird", region: "ch", clip: "a mallard duck", names: { de: "Stockente", en: "mallard", fr: "canard colvert", it: "germano reale" } },
  { latin: "Cygnus olor", wiki: "Mute_swan", group: "bird", region: "ch", clip: "a mute swan", names: { de: "Höckerschwan", en: "mute swan", fr: "cygne tuberculé", it: "cigno reale" } },
  { latin: "Turdus merula", wiki: "Common_blackbird", group: "bird", region: "ch", clip: "a common blackbird", names: { de: "Amsel", en: "blackbird", fr: "merle noir", it: "merlo" } },
  { latin: "Erithacus rubecula", wiki: "European_robin", group: "bird", region: "ch", clip: "a European robin", names: { de: "Rotkehlchen", en: "robin", fr: "rouge-gorge", it: "pettirosso" } },
  { latin: "Parus major", wiki: "Great_tit", group: "bird", region: "ch", clip: "a great tit", names: { de: "Kohlmeise", en: "great tit", fr: "mésange charbonnière", it: "cinciallegra" } },
  { latin: "Pica pica", wiki: "Eurasian_magpie", group: "bird", region: "ch", clip: "a magpie", names: { de: "Elster", en: "magpie", fr: "pie bavarde", it: "gazza" } },
  { latin: "Corvus corone", wiki: "Carrion_crow", group: "bird", region: "ch", clip: "a crow", names: { de: "Rabenkrähe", en: "crow", fr: "corneille", it: "cornacchia" } },
  { latin: "Columba livia", wiki: "Rock_dove", group: "bird", region: "ch", clip: "a city pigeon", names: { de: "Stadttaube", en: "pigeon", fr: "pigeon", it: "piccione" } },
  { latin: "Passer domesticus", wiki: "House_sparrow", group: "bird", region: "ch", clip: "a house sparrow", names: { de: "Haussperling", en: "house sparrow", fr: "moineau domestique", it: "passera europea" } },
  { latin: "Ciconia ciconia", wiki: "White_stork", group: "bird", region: "ch", clip: "a white stork", names: { de: "Weissstorch", en: "white stork", fr: "cigogne blanche", it: "cicogna bianca" } },
  { latin: "Ardea cinerea", wiki: "Grey_heron", group: "bird", region: "ch", clip: "a grey heron", names: { de: "Graureiher", en: "grey heron", fr: "héron cendré", it: "airone cenerino" } },
  { latin: "Buteo buteo", wiki: "Common_buzzard", group: "bird", region: "ch", clip: "a common buzzard", names: { de: "Mäusebussard", en: "buzzard", fr: "buse variable", it: "poiana" } },
  { latin: "Aquila chrysaetos", wiki: "Golden_eagle", group: "bird", region: "ch", clip: "a golden eagle", names: { de: "Steinadler", en: "golden eagle", fr: "aigle royal", it: "aquila reale" } },
  { latin: "Gypaetus barbatus", wiki: "Bearded_vulture", group: "bird", region: "ch", clip: "a bearded vulture", names: { de: "Bartgeier", en: "bearded vulture", fr: "gypaète barbu", it: "gipeto" } },
  { latin: "Pyrrhocorax graculus", wiki: "Alpine_chough", group: "bird", region: "ch", clip: "an Alpine chough", names: { de: "Alpendohle", en: "Alpine chough", fr: "chocard à bec jaune", it: "gracchio alpino" } },
  { latin: "Picus viridis", wiki: "European_green_woodpecker", group: "bird", region: "ch", clip: "a green woodpecker", names: { de: "Grünspecht", en: "green woodpecker", fr: "pic vert", it: "picchio verde" } },
  { latin: "Strix aluco", wiki: "Tawny_owl", group: "bird", region: "ch", clip: "a tawny owl", names: { de: "Waldkauz", en: "tawny owl", fr: "chouette hulotte", it: "allocco" } },
  { latin: "Tyto alba", wiki: "Barn_owl", group: "bird", region: "ch", clip: "a barn owl", names: { de: "Schleiereule", en: "barn owl", fr: "effraie des clochers", it: "barbagianni" } },
  { latin: "Phasianus colchicus", wiki: "Common_pheasant", group: "bird", region: "ch", clip: "a pheasant", names: { de: "Fasan", en: "pheasant", fr: "faisan", it: "fagiano" } },
  { latin: "Gallus gallus", wiki: "Chicken", group: "bird", region: "ch", clip: "a chicken", names: { de: "Huhn", en: "chicken", fr: "poule", it: "gallina" } },
  { latin: "Anser anser", wiki: "Greylag_goose", group: "bird", region: "ch", clip: "a goose", names: { de: "Gans", en: "goose", fr: "oie", it: "oca" } },
  { latin: "Pavo cristatus", wiki: "Indian_peafowl", group: "bird", region: "world", clip: "a peacock", names: { de: "Pfau", en: "peacock", fr: "paon", it: "pavone" } },
  { latin: "Aptenodytes forsteri", wiki: "Emperor_penguin", group: "bird", region: "world", clip: "a penguin", names: { de: "Pinguin", en: "penguin", fr: "pingouin", it: "pinguino" } },
  { latin: "Phoenicopterus roseus", wiki: "Greater_flamingo", group: "bird", region: "eu", clip: "a flamingo", names: { de: "Flamingo", en: "flamingo", fr: "flamant", it: "fenicottero" } },
  { latin: "Haliaeetus albicilla", wiki: "White-tailed_eagle", group: "bird", region: "eu", clip: "a white-tailed eagle", names: { de: "Seeadler", en: "white-tailed eagle", fr: "pygargue à queue blanche", it: "aquila di mare" } },
  { latin: "Corvus corax", wiki: "Common_raven", group: "bird", region: "ch", clip: "a raven", names: { de: "Kolkrabe", en: "raven", fr: "grand corbeau", it: "corvo imperiale" } },
  { latin: "Natrix natrix", wiki: "Grass_snake", group: "reptile", region: "ch", clip: "a grass snake", names: { de: "Ringelnatter", en: "grass snake", fr: "couleuvre à collier", it: "biscia dal collare" } },
  { latin: "Vipera berus", wiki: "Vipera_berus", group: "reptile", region: "ch", clip: "an adder viper snake", names: { de: "Kreuzotter", en: "adder", fr: "vipère péliade", it: "marasso" } },
  { latin: "Anguis fragilis", wiki: "Slow_worm", group: "reptile", region: "ch", clip: "a slow worm", names: { de: "Blindschleiche", en: "slow worm", fr: "orvet", it: "orbettino" } },
  { latin: "Lacerta agilis", wiki: "Sand_lizard", group: "reptile", region: "ch", clip: "a sand lizard", names: { de: "Zauneidechse", en: "sand lizard", fr: "lézard des souches", it: "lucertola agile" } },
  { latin: "Zootoca vivipara", wiki: "Viviparous_lizard", group: "reptile", region: "ch", clip: "a viviparous lizard", names: { de: "Waldeidechse", en: "viviparous lizard", fr: "lézard vivipare", it: "lucertola vivipara" } },
  { latin: "Emys orbicularis", wiki: "European_pond_turtle", group: "reptile", region: "ch", clip: "a pond turtle", names: { de: "Sumpfschildkröte", en: "pond turtle", fr: "cistude", it: "testuggine palustre" } },
  { latin: "Testudo hermanni", wiki: "Hermann's_tortoise", group: "reptile", region: "eu", clip: "a tortoise", names: { de: "Landschildkröte", en: "tortoise", fr: "tortue terrestre", it: "tartaruga di terra" } },
  { latin: "Crocodylus niloticus", wiki: "Nile_crocodile", group: "reptile", region: "world", clip: "a crocodile", names: { de: "Krokodil", en: "crocodile", fr: "crocodile", it: "coccodrillo" } },
  { latin: "Iguana iguana", wiki: "Green_iguana", group: "reptile", region: "world", clip: "a green iguana", names: { de: "Leguan", en: "iguana", fr: "iguane", it: "iguana" } },
  { latin: "Bufo bufo", wiki: "Common_toad", group: "amphibian", region: "ch", clip: "a common toad", names: { de: "Erdkröte", en: "common toad", fr: "crapaud commun", it: "rospo comune" } },
  { latin: "Rana temporaria", wiki: "Common_frog", group: "amphibian", region: "ch", clip: "a common frog", names: { de: "Grasfrosch", en: "common frog", fr: "grenouille rousse", it: "rana temporaria" } },
  { latin: "Salamandra salamandra", wiki: "Fire_salamander", group: "amphibian", region: "ch", clip: "a fire salamander", names: { de: "Feuersalamander", en: "fire salamander", fr: "salamandre tachetée", it: "salamandra pezzata" } },
  { latin: "Triturus cristatus", wiki: "Northern_crested_newt", group: "amphibian", region: "ch", clip: "a newt", names: { de: "Kammolch", en: "crested newt", fr: "triton crêté", it: "tritone crestato" } },
  { latin: "Hyla arborea", wiki: "European_tree_frog", group: "amphibian", region: "ch", clip: "a European tree frog", names: { de: "Laubfrosch", en: "tree frog", fr: "rainette verte", it: "raganella" } },
  { latin: "Perca fluviatilis", wiki: "European_perch", group: "fish", region: "ch", clip: "a perch fish", names: { de: "Flussbarsch", en: "perch", fr: "perche", it: "persico" } },
  { latin: "Esox lucius", wiki: "Northern_pike", group: "fish", region: "ch", clip: "a pike fish", names: { de: "Hecht", en: "pike", fr: "brochet", it: "luccio" } },
  { latin: "Salmo trutta", wiki: "Brown_trout", group: "fish", region: "ch", clip: "a brown trout", names: { de: "Forelle", en: "brown trout", fr: "truite", it: "trota" } },
  { latin: "Cyprinus carpio", wiki: "Common_carp", group: "fish", region: "ch", clip: "a carp", names: { de: "Karpfen", en: "carp", fr: "carpe", it: "carpa" } },
  { latin: "Carcharodon carcharias", wiki: "Great_white_shark", group: "fish", region: "world", clip: "a great white shark", names: { de: "Weisser Hai", en: "great white shark", fr: "grand requin blanc", it: "grande squalo bianco" } },
  { latin: "Apis mellifera", wiki: "Honey_bee", group: "insect", region: "ch", clip: "a honey bee", names: { de: "Honigbiene", en: "honey bee", fr: "abeille", it: "ape" } },
  { latin: "Bombus terrestris", wiki: "Buff-tailed_bumblebee", group: "insect", region: "ch", clip: "a bumblebee", names: { de: "Hummel", en: "bumblebee", fr: "bourdon", it: "bombo" } },
  { latin: "Coccinella septempunctata", wiki: "Coccinella_septempunctata", group: "insect", region: "ch", clip: "a seven-spot ladybird", names: { de: "Marienkäfer", en: "ladybird", fr: "coccinelle", it: "coccinella" } },
  { latin: "Papilio machaon", wiki: "Papilio_machaon", group: "insect", region: "ch", clip: "a swallowtail butterfly", names: { de: "Schwalbenschwanz", en: "swallowtail", fr: "machaon", it: "macaone" } },
  { latin: "Inachis io", wiki: "Aglais_io", group: "insect", region: "ch", clip: "a peacock butterfly", names: { de: "Tagpfauenauge", en: "peacock butterfly", fr: "paon du jour", it: "pavone di giorno" } },
  { latin: "Aglais urticae", wiki: "Small_tortoiseshell", group: "insect", region: "ch", clip: "a small tortoiseshell butterfly", names: { de: "Kleiner Fuchs", en: "small tortoiseshell", fr: "petite tortue", it: "vanessa dell'ortica" } },
  { latin: "Pieris brassicae", wiki: "Pieris_brassicae", group: "insect", region: "ch", clip: "a cabbage white butterfly", names: { de: "Kohlweissling", en: "cabbage white", fr: "piéride du chou", it: "cavolaia" } },
  { latin: "Libellula depressa", wiki: "Broad-bodied_chaser", group: "insect", region: "ch", clip: "a dragonfly", names: { de: "Libelle", en: "dragonfly", fr: "libellule", it: "libellula" } },
  { latin: "Formica rufa", wiki: "Formica_rufa", group: "insect", region: "ch", clip: "a red wood ant", names: { de: "Waldameise", en: "wood ant", fr: "fourmi rousse", it: "formica rossa" } },
  { latin: "Vespa crabro", wiki: "European_hornet", group: "insect", region: "ch", clip: "a European hornet", names: { de: "Hornisse", en: "hornet", fr: "frelon", it: "calabrone" } },
  { latin: "Vespula vulgaris", wiki: "Common_wasp", group: "insect", region: "ch", clip: "a wasp", names: { de: "Wespe", en: "wasp", fr: "guêpe", it: "vespa" } },
  { latin: "Musca domestica", wiki: "Housefly", group: "insect", region: "ch", clip: "a housefly", names: { de: "Stubenfliege", en: "housefly", fr: "mouche", it: "mosca" } },
  { latin: "Tettigonia viridissima", wiki: "Great_green_bush-cricket", group: "insect", region: "ch", clip: "a grasshopper", names: { de: "Heuschrecke", en: "grasshopper", fr: "sauterelle", it: "cavalletta" } },
  { latin: "Lucanus cervus", wiki: "Lucanus_cervus", group: "insect", region: "ch", clip: "a stag beetle", names: { de: "Hirschkäfer", en: "stag beetle", fr: "lucane", it: "cervo volante" } },
  { latin: "Mantis religiosa", wiki: "European_mantis", group: "insect", region: "eu", clip: "a praying mantis", names: { de: "Gottesanbeterin", en: "praying mantis", fr: "mante religieuse", it: "mantide" } },
  { latin: "Araneus diadematus", wiki: "European_garden_spider", group: "other", region: "ch", clip: "a garden spider", names: { de: "Gartenkreuzspinne", en: "garden spider", fr: "épeire diadème", it: "ragno di giardino" } },
  { latin: "Tegenaria domestica", wiki: "Barn_funnel_weaver", group: "other", region: "ch", clip: "a house spider", names: { de: "Hauswinkelspinne", en: "house spider", fr: "tégénaire", it: "ragno domestico" } },
  { latin: "Helix pomatia", wiki: "Helix_pomatia", group: "other", region: "ch", clip: "a Roman snail", names: { de: "Weinbergschnecke", en: "Roman snail", fr: "escargot de Bourgogne", it: "chiocciola" } },
  { latin: "Arianta arbustorum", wiki: "Arianta_arbustorum", group: "other", region: "ch", clip: "a brown snail", names: { de: "Gefleckte Schnirkelschnecke", en: "copse snail", fr: "escargot des bois", it: "chiocciola dei cespugli" } },
  { latin: "Lumbricus terrestris", wiki: "Lumbricus_terrestris", group: "other", region: "ch", clip: "an earthworm", names: { de: "Regenwurm", en: "earthworm", fr: "ver de terre", it: "lombrico" } },
  { latin: "Astacus astacus", wiki: "Astacus_astacus", group: "other", region: "ch", clip: "a crayfish", names: { de: "Flusskrebs", en: "crayfish", fr: "écrevisse", it: "gambero di fiume" } },
];

export function inSwitzerland(lat: number, lon: number): boolean {
  return lat >= 45.75 && lat <= 47.85 && lon >= 5.9 && lon <= 10.55;
}
